### ISSUE TITLE
total_records nested SELECT is slow

### ISSUE THREAD

**Issue by sheldond** [code-and-effect/effective_datatables#24]
Hi Matt!

I've been testing effective_datatables with production data and found that the query made in total_records is quite slow for me, over 4 seconds in my case. There may be some optimization I can make in our db, but I believe it's fundamentally slow because the nested select is selecting all records and all columns in the table. 

An example query like:
```
SELECT COUNT(*) FROM (SELECT ... WHERE (...)) AS datatables_total_count
```
This query takes about 4100ms.

If I remove the nested select, and perform the same query but just selecting a count:
```
SELECT COUNT(*) FROM ... WHERE (...)
```
Then the count query takes about 20ms.

Maybe we can improve total_records query to use activerecord `.count` when possible, and fallback to the current query when not?

Do you think you could provide an example of when `.count` does not work? If so maybe I could work on a solution.

Thanks!
Sheldon

**Comment by matt-riemer** [comment]
Hey @sheldond ,

This is a great idea! Anything I (we?) can do to speed up a method that's used on every datatable, is worth lots of attention!

I honestly don't remember why I used the SELECT COUNT from collection instead of just using `.count` on the ActiveRecord resource.   My foggy memory tells me it has something to do with a collection that is using its own .select() calls, or maybe a complex join query that was doing the wrong thing. I would have run into this almost two years ago.

I think your idea of doing the fast way first, then fallback to the existing SELECT COUNT from collection method if that doesn't work, is the right approach.  Perhaps making this a little dsl method to indicate "fallback_to_conservative_count_method" so the old method is still available.

I will have time to work on this issue in the next few days if you want to wait for me to release another version.  

Or if you're the kind of person that wants to tinker, I think this is an easyish thing to add:

I would follow the `default_entries` pattern, as per models/effective/effective_datatable/dsl/datatable.rb and just create an instance variable to revert to the existing count behavior.

Thanks for your fresh eyes on this gem!  :)

**Comment by sheldond** [comment]
Thanks @matt-riemer! It'd be super great if you could take a shot at it as I'm not 100% sure what you have in mind. No pressure though, if you can't get to this, I may look at it later.

**Comment by matt-riemer** [comment]
Hey again @sheldond 

Try out effective_datatables 2.6.4

Here's the relevant commit:

https://github.com/code-and-effect/effective_datatables/commit/2614285b7448130526f4b8fa5e8929a03c64fb39

Does this work for you on MySql?
Does it actually speed anything up? :)

Thanks,

**Comment by sheldond** [comment]
Hi @matt-riemer,

This is working great, and my count queries are now ~20ms.

Perfect! Thanks so much for taking the time for this! 😄 

Sheldon
