### ISSUE TITLE
how can add custom filter option with date range filter and  greedy search

### ISSUE THREAD

**Issue by uzaif313** [code-and-effect/effective_datatables#64]
first of all thanks for awesome gem :+1: 

I want to add greedy search in my current table and with it. i also want to add date range filter which is based on date-range picker

**Comment by matt-riemer** [comment]
What date-range picker library would you want to implement? :)

Adding the input might not be too difficult...have you seen effective_form_inputs gem? that's what I'm using for all my "wrap javascript library in a rails form helper" stuff.

But actually working with a date range instead of a singular value might require some changes to the finder.

effective_datatables uses
https://github.com/code-and-effect/effective_datatables/blob/master/app/models/effective/datatable_value_tool.rb

the datables value tool to do all the ordering/searching of arrays.

And delegates any SQL/activerecord finder stuff to an Effective::Resource object, which is in another gem, effective_resources,

It ends up here:

https://github.com/code-and-effect/effective_resources/blob/master/app/models/effective/resources/relation.rb

and maybe here:

https://github.com/code-and-effect/effective_resources/blob/master/app/models/effective/resources/forms.rb


Accepting PRs! I'd love to see what ideas you have.

Cheers :)

**Comment by matt-riemer** [comment]
This is where all the search options are initialized:

https://github.com/code-and-effect/effective_datatables/blob/master/app/models/effective/effective_datatable/resource.rb#L110

And here is now they're called. Based on the :as value

https://github.com/code-and-effect/effective_datatables/blob/master/app/helpers/effective_datatables_private_helper.rb#L33

**Comment by matt-riemer** [comment]
FYI,

In effective_form_inputs
https://github.com/code-and-effect/effective_form_inputs/blob/master/app/assets/javascripts/effective_date_picker/initialize.js.coffee

It's not a date range plugin...but it automatically supports linked date pickers, as per:

http://eonasdan.github.io/bootstrap-datetimepicker/Options/

So if you have two form inputs with names like "item[start_at]" and "item[end_at]", selecting a time on the start_at picker, will set the minDate of the end_at datepicker.  Linking them, kinda...

**Comment by uzaif313** [comment]
can we add lazy load in data tables and fixed header in tables?

**Comment by matt-riemer** [comment]
lazy load is a bad idea because you end up just making 2 requests instead of just 1.  

Imho, you might as well prepopulate the table with the first page of records on the first GET request / initial render, instead of loading an empty datatable and then making an ajax request for the data. Especially if there's more than 1 datatable being displayed per page. T

hat's the approach I've always used! You're welcome to play with it tho, the javascript library does support it.  Checkout the javascript init options at 

https://github.com/code-and-effect/effective_datatables/blob/master/app/assets/javascripts/effective_datatables/initialize.js.coffee

as the datatables javascript library does support this approach.

As for the fixed headers, I I have tried implementing them before before, but wasn't able to get it working properly...

https://datatables.net/extensions/fixedheader/

You're welcome to give it a shot.  Should just need to drop in the fixedheader specific javascript and css file to get it working in this gem.  Cheers.

**Comment by matt-riemer** [comment]
yea, infinite scroll would be cool :)

I tried implementing this a year or two ago, but it worked really crappy with an ajax data source.  Maybe datatables.net js library has improved since then?

**Comment by uzaif313** [comment]
can you provide demo of that infinite scroll and i am facing issue while searching or sorting its shows me alert which contain text like 
 `data table not found`

**Comment by uzaif313** [comment]
can you provide demo of that infinite scroll and i am facing issue while searching or sorting its shows me alert which contain text like 
 `data table not found`

**Comment by uzaif313** [comment]
can you provide demo of that infinite scroll and i am facing issue while searching or sorting its shows me alert which contain text like 
 `data table not found`

**Comment by matt-riemer** [comment]
nah, sorry I don't have any code lying around for that...check out some of the other datatables.net javascript libraries that are included...follow that pattern..

**Comment by uzaif313** [comment]
while searching or sorting its shows me alert which contain text like
data table not found

**Comment by matt-riemer** [comment]
just find the line it errors on, then `binding.pry` figure out why it can't find it :)

It might be worth starting in /app/controllers/effective/datatables_controller.rb

**Comment by uzaif313** [comment]
is it possible to retrieve collection in controller and use it in datatable class?

**Comment by matt-riemer** [comment]
you could initialize the datatable in a controller

@datatable = Klass.new(self)

then call @datatable.to_json or @datatable.collection on it.

Search for the hooks, check out `def finalize`

https://github.com/code-and-effect/effective_datatables/blob/master/app/models/effective/effective_datatable/hooks.rb
