### ISSUE TITLE
Optional select2

### ISSUE THREAD

**Issue by Nerian** [code-and-effect/effective_datatables#88]
Hi,

Currently when I do:

```
filter :year, Time.current.year, as: :select, collection: year_collection, include_blank: false
```

It uses effective_bootstrap's select2 implementation. Is there a way to disable it on a filter by filter basis?  I would like this particular filter to not use select2. I would like just plain old style select without any fancy.

Is there a way to do this?

**Comment by matt-riemer** [comment]
Haha, nope...there is no way to make it a regular select field. Yay and Boo opinionated software? :)

There is no way, because the `filters` partial calls `effective_form_with`, from effective_bootstrap gem, which is a small wrapper around the new rails form_with, but totally replaces `f.text_field` and `f.select` type helpers.

FYI, Rails has soft deprecated `form_tag` and `form_for`. And around the time I was building all the boootstrap4 stuff, I had decided to ditch simple_form for a bunch of reasons.

Anyway.  You can totally override the `/app/views/effective/datatables/_filters.html.haml` partial and do what you need there!

https://github.com/code-and-effect/effective_datatables/blob/master/app/views/effective/datatables/_filters.html.haml

**Comment by Nerian** [comment]
But if I change that partial I would be changing it for all datatables, right?

This upgrade to rails 4 is being very complicated. I am using SimpleForm and ChosenJS, and some other calendar tool, so the migration to effective_datatables – and thus effective-bootstrap – is not so straight forward 🤦‍♂️ .  

Some tables are pretty broken. Right now the "Apply" button doesn't work. It just sends a regular request, but ignoring all filters – so nothing is filtered. I am trying to figure out what is wrong. Also the filters ignore `include_blank` (but I saw your answer in the other issue – I may PR ).

<img width="932" alt="captura de pantalla 2018-10-08 a las 18 27 09" src="https://user-images.githubusercontent.com/259568/46621489-dd31ed80-cb27-11e8-93d6-f033cd80b1f3.png">

**Comment by matt-riemer** [comment]
Yep, it would be changing it for all datatables partials then.

You could always initialize just that one datatable with an attribute. `@datatable = InvoicesDatatable.new(oldschool_select: true)` and, in the partial, check for `datatable.attributes[:oldschool_select]` and do the right thing...

**Comment by matt-riemer** [comment]
Select2 is great tho. It's like, the least bad of the javascript select libraries!!

**Comment by matt-riemer** [comment]
Also, imho, upgrade straight to rails 5.

Why bother with rails4 at all?  Dunno the size/scope of your app. I'm sure the answer is: "reasons" :)

**Comment by Nerian** [comment]
Oh I said Rails 4. I was thinking Bootstrap 4 :)  I always on the latest Rails.

**Comment by Nerian** [comment]
I will check Select2 for sure. I saw that it support tags, so that would be nice. I am currently using another library for tagging, besides chosenjs. Once I upgrade all these stuff I will be able to cut a big size of the JS file :)
