### ISSUE TITLE
Cookie gets too big

### ISSUE THREAD

**Issue by eleos** [code-and-effect/effective_datatables#98]
I seem to be having an issue when using effective_datatables in our production environment. After loading x amount of datatables the cookie gets too big and NGINX stops processing the request.

Nginx error log:
upstream sent too big header while reading response header from upstream

When I remove the _effective_dt cookie all loads again perfect. I modified the nginx server for now to allow larger cookies. But this would only be a fix till it happens again. The cookie gets bigger with every new datatable loaded and will reach the maximum only a bit later.

**Comment by matt-riemer** [comment]
Hey eleos!

Sorry to hear you're running into production issues :(

Yep, effective_datatables uses a cookie to store/bounce between client and server any attributes the datatable was initialized with.  We use a signed cookie so that it's secure.

effective_datatables stores just 1 cookie, but that cookie contains the Hash of the "x last" datatable attributes, upto a max byte size, then it deletes the oldest ones.  It's a FILO buffer.

https://github.com/code-and-effect/effective_datatables/blob/master/app/models/effective/effective_datatable/cookie.rb#L56

So the cookie "should" be limiting itself to a byte size of 2000 characters (I'm not sure the exact byte size of that, maybe 3.5kb?)

My question back at you:

1.) What attributes are you initializing any datatables with? Are you assigning objects in your attributes? Don't do that!  Stick to Integers, Strings and Booleans.

UsersDatatable.new(user_id: 3)   # good

UsersDatatable.new(user: User.find(3))   # bad

2.)  Is your site also using like a lot of other cookies too?  My understanding is that all the cookies for each site are basically added together and transmitted in the HTTP header.

So if you had like a very large datatables cookie, but not quite over the limit, another large cookie would put it over the limit.

I run effective_datatables on about 50 different sites, from rails3 to rails 5, varying puma, passenger and thin. All hosted on Heroku. I haven't run into this issue on production!

3.) If this is a continuing issue for you, I can extract that max byte size constant, and make it user configurable

Cheers

**Comment by eleos** [comment]
This can be closed than. Another cookie in our system is also pretty big (holds account information). Together they pushed header limit. The modification on the nginx server should be sufficient then. Thanks for the support!

**Comment by matt-riemer** [comment]
Hey again eleos,

I have added a config option for the max cookie size!

In effective_datatables 3.5.3 or 4.3.17 and higher, there will be a config option in the `config/initializers/effective_datatables.rb` file for `config.max_cookie_size` set to the default `2000`

Maybe just changing this to `1000` would be a good fix for you!
